language: python

python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.5"
install:
    - pip install nose

script:
  - python setup.py install
  - rake lint
  - nosetests test/unit test/integration
